library constants;

const COLOR_ACCENT = 0xFFFFFFFF;
const COLOR_PRIMARY_DARK = 0xFFFFFFFF;
const COLOR_BACKGROUND = 0xFFFAFAFA;
const COLOR_PRIMARY = 0xFFFFFFFF;
const COLOR_WHITE = 0xFFffffff;
const COLOR_TEXT_PRIMARY = 0xFF231F20;
const COLOR_TEXT_SECONDARY = 0xFF7f8c8d;

const COLOR_BLUE = 0xFF4285F4;
const COLOR_RED = 0xFFEA4335;
const COLOR_YELLOW = 0xFFFBBC05;
const COLOR_GREEN = 0xFF34A853;
const COLOR_YELLO_GREEN = 0xFFBEC100;
const COLOR_YELLO_LEMON = 0xFFfff44f;


const APP_TITLE = 'Instgram';
const APP_SUBTITLE = 'Share your story';